name: checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/checks.yml'
      - '**/lib/**'
      - '**/android/**'
      - '**/ios/**'
      - '**/web/**'
      - '**/macos/**'
      - '**/windows/**'
      - '**/pubspec.yaml'
      - '**/test/**'
      - '**/assets/**'

jobs:
  analyze:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} analysis on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
          - 'dev'
        package:
          - 'funvas'
          - 'funvas_gallery'
          - 'funvas_tweets'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: ${{ matrix.channel }}
      - name: pub get
        run: flutter pub get
        working-directory: ${{ matrix.package }}
      - name: dart format
        working-directory: ${{ matrix.package }}
        run: dart format . --fix --set-exit-if-changed
      - run: dart analyze
        working-directory: ${{ matrix.package }}
